// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using inzynierka.Models;

#nullable disable

namespace inzynierka.Migrations
{
    [DbContext(typeof(InzynierkaContext))]
    [Migration("20251206222423_FixSuggestionsSeed")]
    partial class FixSuggestionsSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.31");

            modelBuilder.Entity("inzynierka.Models.FixSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FixSuggestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RuleId = "color-contrast",
                            Suggestion = "Zwiększ kontrast tekstu do minimum 4.5:1."
                        },
                        new
                        {
                            Id = 2,
                            RuleId = "image-alt",
                            Suggestion = "Dodaj opis alternatywny alt=\"\" do obrazka."
                        },
                        new
                        {
                            Id = 3,
                            RuleId = "button-name",
                            Suggestion = "Dodaj treść przycisku lub aria-label."
                        },
                        new
                        {
                            Id = 4,
                            RuleId = "link-name",
                            Suggestion = "Nadaj linkowi opisowy tekst, zamiast 'kliknij tutaj'."
                        },
                        new
                        {
                            Id = 5,
                            RuleId = "heading-order",
                            Suggestion = "Utrzymuj logiczną hierarchię nagłówków H1 → H2 → H3."
                        },
                        new
                        {
                            Id = 6,
                            RuleId = "region",
                            Suggestion = "Dodaj landmarki: <main>, <nav>, <header>, <footer>."
                        },
                        new
                        {
                            Id = 7,
                            RuleId = "landmark-one-main",
                            Suggestion = "Upewnij się, że strona ma tylko jeden element <main>."
                        },
                        new
                        {
                            Id = 8,
                            RuleId = "aria-required-parent",
                            Suggestion = "Umieść element w poprawnym rodzicu zgodnym z rolą ARIA."
                        },
                        new
                        {
                            Id = 9,
                            RuleId = "aria-required-children",
                            Suggestion = "Dodaj wymagane elementy potomne wymagane przez rolę."
                        },
                        new
                        {
                            Id = 10,
                            RuleId = "label",
                            Suggestion = "Dodaj <label for=\"id\"> do każdego pola formularza."
                        },
                        new
                        {
                            Id = 11,
                            RuleId = "autocomplete-valid",
                            Suggestion = "Używaj poprawnych wartości atrybutu autocomplete."
                        },
                        new
                        {
                            Id = 12,
                            RuleId = "focus-order",
                            Suggestion = "Zapewnij logiczną kolejność przechodzenia klawiszem TAB."
                        },
                        new
                        {
                            Id = 13,
                            RuleId = "focus-visible",
                            Suggestion = "Dodaj wyraźny styl focus, np. outline."
                        },
                        new
                        {
                            Id = 14,
                            RuleId = "keyboard",
                            Suggestion = "Upewnij się, że każdy element interaktywny działa z klawiatury."
                        },
                        new
                        {
                            Id = 15,
                            RuleId = "html-lang",
                            Suggestion = "Ustaw atrybut <html lang=\"pl\"> lub odpowiedni."
                        },
                        new
                        {
                            Id = 16,
                            RuleId = "empty-heading",
                            Suggestion = "Usuń nagłówki bez treści."
                        },
                        new
                        {
                            Id = 17,
                            RuleId = "list",
                            Suggestion = "Używaj <ul>, <ol> zamiast list w <div>."
                        },
                        new
                        {
                            Id = 18,
                            RuleId = "listitem",
                            Suggestion = "Upewnij się, że <li> występuje tylko wewnątrz <ul> lub <ol>."
                        },
                        new
                        {
                            Id = 19,
                            RuleId = "definition-list",
                            Suggestion = "Popraw strukturę <dl>: używaj <dt> i <dd>."
                        },
                        new
                        {
                            Id = 20,
                            RuleId = "page-has-heading-one",
                            Suggestion = "Dodaj dokładnie jeden nagłówek <h1> na stronę."
                        },
                        new
                        {
                            Id = 21,
                            RuleId = "aria-hidden-focus",
                            Suggestion = "Usuń możliwość focusowania elementów aria-hidden."
                        },
                        new
                        {
                            Id = 22,
                            RuleId = "duplicate-id",
                            Suggestion = "Upewnij się, że każde ID na stronie jest unikalne."
                        },
                        new
                        {
                            Id = 23,
                            RuleId = "iframe-title",
                            Suggestion = "Dodaj atrybut title do iframe."
                        },
                        new
                        {
                            Id = 24,
                            RuleId = "svg-img-alt",
                            Suggestion = "Dodaj <title> lub aria-label do elementu SVG."
                        },
                        new
                        {
                            Id = 25,
                            RuleId = "interactive-supports-focus",
                            Suggestion = "Dodaj tabindex=\"0\" dla elementów interaktywnych."
                        },
                        new
                        {
                            Id = 26,
                            RuleId = "tabindex",
                            Suggestion = "Unikaj tabindex większego niż 0 — używaj tabindex=\"0\"."
                        },
                        new
                        {
                            Id = 27,
                            RuleId = "skip-link",
                            Suggestion = "Dodaj link 'Przejdź do treści' na początku strony."
                        },
                        new
                        {
                            Id = 28,
                            RuleId = "form-field-multiple-labels",
                            Suggestion = "Usuń duplikaty etykiet <label>."
                        },
                        new
                        {
                            Id = 29,
                            RuleId = "input-button-name",
                            Suggestion = "Dodaj wartość value lub aria-label dla input type='button'."
                        },
                        new
                        {
                            Id = 30,
                            RuleId = "target-size",
                            Suggestion = "Zwiększ obszar klikalny elementów do min. 24px."
                        },
                        new
                        {
                            Id = 31,
                            RuleId = "no-autoplay-audio",
                            Suggestion = "Wyłącz automatyczne odtwarzanie dźwięku."
                        },
                        new
                        {
                            Id = 32,
                            RuleId = "video-caption",
                            Suggestion = "Dodaj napisy do filmów."
                        },
                        new
                        {
                            Id = 33,
                            RuleId = "video-description",
                            Suggestion = "Dodaj audiodeskrypcję do materiału video."
                        },
                        new
                        {
                            Id = 34,
                            RuleId = "aria-valid-attr-value",
                            Suggestion = "Popraw wartości atrybutów ARIA."
                        },
                        new
                        {
                            Id = 35,
                            RuleId = "aria-valid-attr",
                            Suggestion = "Używaj tylko dostępnych atrybutów aria-*."
                        },
                        new
                        {
                            Id = 36,
                            RuleId = "aria-input-field-name",
                            Suggestion = "Dodaj nazwę pola za pomocą aria-label lub label."
                        },
                        new
                        {
                            Id = 37,
                            RuleId = "aria-toggle-field-name",
                            Suggestion = "Dodaj nazwę dla elementów przełączalnych."
                        },
                        new
                        {
                            Id = 38,
                            RuleId = "scrollable-region-focusable",
                            Suggestion = "Dodaj tabindex dla przewijalnych regionów."
                        },
                        new
                        {
                            Id = 39,
                            RuleId = "live-region",
                            Suggestion = "Ustaw aria-live=\"polite\" dla dynamicznej treści."
                        },
                        new
                        {
                            Id = 40,
                            RuleId = "duplicate-live-region",
                            Suggestion = "Usuń duplikaty regionów aria-live."
                        },
                        new
                        {
                            Id = 41,
                            RuleId = "select-name",
                            Suggestion = "Dodaj label do pola <select>."
                        },
                        new
                        {
                            Id = 42,
                            RuleId = "fieldset",
                            Suggestion = "Używaj <fieldset> do grupowania powiązanych pól formularza."
                        },
                        new
                        {
                            Id = 43,
                            RuleId = "audio-description",
                            Suggestion = "Dodaj alternatywny opis audio."
                        },
                        new
                        {
                            Id = 44,
                            RuleId = "meta-viewport-large",
                            Suggestion = "Używaj poprawnego meta viewport dla urządzeń mobilnych."
                        },
                        new
                        {
                            Id = 45,
                            RuleId = "presentation-role-conflict",
                            Suggestion = "Usuń role='presentation' z elementów interaktywnych."
                        },
                        new
                        {
                            Id = 46,
                            RuleId = "empty-table-header",
                            Suggestion = "Nagłówki tabeli muszą mieć treść."
                        },
                        new
                        {
                            Id = 47,
                            RuleId = "th-has-data-cells",
                            Suggestion = "Nagłówki <th> muszą odpowiadać komórkom danych."
                        },
                        new
                        {
                            Id = 48,
                            RuleId = "table-duplicate-name",
                            Suggestion = "Dodaj różne nazwy dla tabel."
                        },
                        new
                        {
                            Id = 49,
                            RuleId = "frame-title",
                            Suggestion = "Dodaj opisowy tytuł dla ramki lub iframe."
                        },
                        new
                        {
                            Id = 50,
                            RuleId = "autocomplete-attribute",
                            Suggestion = "Zweryfikuj wartości atrybutów autocomplete wg specyfikacji."
                        });
                });

            modelBuilder.Entity("inzynierka.Models.ScanModel", b =>
                {
                    b.Property<int>("ScanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullResultJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScanId");

                    b.HasIndex("UserId");

                    b.ToTable("Scan");
                });

            modelBuilder.Entity("inzynierka.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerificationTokenExpires")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("inzynierka.Models.ViolationModel", b =>
                {
                    b.Property<int>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Help")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ViolationId");

                    b.HasIndex("ScanId");

                    b.ToTable("Vialations");
                });

            modelBuilder.Entity("inzynierka.Models.ScanModel", b =>
                {
                    b.HasOne("inzynierka.Models.UserModel", "User")
                        .WithMany("Scans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("inzynierka.Models.ViolationModel", b =>
                {
                    b.HasOne("inzynierka.Models.ScanModel", "Scan")
                        .WithMany("Violations")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("inzynierka.Models.ScanModel", b =>
                {
                    b.Navigation("Violations");
                });

            modelBuilder.Entity("inzynierka.Models.UserModel", b =>
                {
                    b.Navigation("Scans");
                });
#pragma warning restore 612, 618
        }
    }
}
